### ISSUE TITLE
[FATAL] Initializer

### ISSUE THREAD

**Issue by zydar84** [TorchAPI/Torch#544] opened 2023-04-15 09:15 UTC
hey there is this issue i stumpel over
`
09:50:32.4060 [FATAL] Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_AddIdSafe (Type type, MyStringId id) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 135 at Torch.Patches.ObjectFactoryInitPatch. ComponentTypeFactory_Register FromAssemblySafe (Assembly assembly) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 121 at Torch.Patches.ObjectFactoryInitPatch. ForceRegisterAssemblies() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 58
at Torch. TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 315
at Torch.Server. TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch. Server\TorchServer.cs:line 145
at Torch.Server.Initializer.<Run>b___23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch. Server\Initializer.cs:line 156
at System.Threading.ExecutionContext.RunInternal (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_AddIdSafe (Type type, MyStringId id) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 135
at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_Register FromAssemblySafe (Assembly assembly) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 121
at Torch.Patches.ObjectFactoryInitPatch. ForceRegisterAssemblies() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 58
at Torch. TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 315
at Torch.Server. TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 145
at Torch.Server.Initializer.<Run>b___23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\Initializer.cs:line 156
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading. ThreadHelper.ThreadStart()`

**Comment by Neshfi** [comment] 2023-04-15 18:37
This is a duplicate of https://github.com/TorchAPI/Torch/issues/540.
@zydar84 I suggest you try my [suggested workaround](https://github.com/TorchAPI/Torch/issues/540#issuecomment-1507608543) described in that issue.

**Comment by Bishbash777** [comment] 2023-04-15 23:13
Closing, you need to update manually

**Closed by Bishbash777** 2023-04-15 23:13 UTC
