### ISSUE TITLE
On restart, world is reverted to the state when Torch was opened

### ISSUE THREAD

**Issue by juanpbouquet** [TorchAPI/Torch#352] opened 2019-10-03 17:56 UTC
**Torch Version:** 1.3.1.88 **SE Version:** 1.192.104

### Expected Behavior
Stopping and restarting the server should keep the changes on the world, including markers, object ownership, factions, etc.

### Observed Behavior
When re-starting the server, the Sandbox.sbc file is reverted to its original content (the one when the Torch Server started first time). I had the server running non-stop for about 40hs and stopped and restarted and everything was deleted. 

### Steps to Reproduce
1. Start the server in any world.
2. Join game and create a GPS marker anywhere.
3. Stop the server
4. Start the server again and the Sandbox.sbc is reverted to the exact one when the TorchServer app started. 

### Additional notes
- The revert is made just when you click on 'Start' button, even before DS starts (while running SteamCMD)
- Last Saved and World size on 'Configuration' tab never updates even if you save your world manually. 
- Bug can be avoided by closing Torch application before starting the server again, this way 'Last Saved' is updated and the proper save is loaded. 
- Save game feature works perfectly, the Sandbox.sbc is updated when you save, but reverted on start.
- I don't know ANYTHING about programming, but it seems to me that the Sandbox.sbc file is loaded only on Torch start and it overwrites the recently saved game with the initial one.

**Comment by KuroshiShirone** [comment] 2019-10-03 19:13
Sounds like you have "ignore last session" checked to me, check the configuration tab for this option and uncheck it it is checked

**Comment by juanpbouquet** [comment] 2019-10-04 16:45
I triple checked and verified that there's no such option like 'Ignore Last Session' or similar on the Configuration tab. Is there any config file I can check for?

**Comment by N1Ran** [comment] 2019-10-04 16:50
There's a new config file the overwrites the settings as long as it's present. In the world folder, you'll see a file called Sandbox_config.sbc, either delete it or edit it to match the world settings

**Comment by Jimmacle** [comment] 2019-10-04 17:00
Is the file specifically reverted or are changes not being saved to disk in the first place?

**Comment by juanpbouquet** [comment] 2019-10-04 17:15
It's reverted on the moment I click 'Start', the changes are properly saved
on autosave (every 5 minutes), !save command, and /save command.

**Comment by swifty02** [comment] 2019-10-12 17:11
did you ever find a solution to this problem?

**Comment by N1Ran** [comment] 2019-10-12 17:22
yes, upgrade your Torch and make sure you click Save before starting whenever you make changes using the gui

**Comment by swifty02** [comment] 2019-10-12 17:25
using latest torch and always click save

**Comment by N1Ran** [comment] 2019-10-12 17:26
oh?  Explain your issue in detail and provide log

**Comment by swifty02** [comment] 2019-10-12 17:28
same issue as the post author only difference ive noticed is that the player bodies seem to duplicate, if i manually set the ignorelastsave option to false everything loads fine, but when i stop then start the server the option changes back to true and all above mentioned problem appear. logs are clean as they have been checked by jimmacle

**Comment by avanheuvelen** [comment] 2019-10-17 20:34
I have the same issue as swifty02.

- stop server
- click save
- quit torch
- start torch
- start server

Block ownership, Faction info, GPS coordinates, all gone. My body is there, but transmits the name of someone else who's playing on the server. (Presumably because he logged in before me.)

**Comment by Nessiroj** [comment] 2019-10-28 15:28
Having the same issues on my dedicated server. As soon as the server gets a shutdown everything factionwise en ownerwhipwise is gone. The building are still there only without any owner. GPS gone (not strange faction is gone). And seeing yourself standing on the last position when shutting down the server (aka there is 2 of me).

Tried Torch with and without mods, no difference.
(problem started about 3 weeks ago after updating torch due to a SE update).

Currently running the server on the official software without those problems (performance issues tough hence why i was checking if there was an update on this.)

**Comment by Jimmacle** [comment] 2019-11-11 00:05
I think I finally found the issue, let your server auto-update or try this build to double check: https://build.torchapi.net/job/Torch/job/Torch/job/master/94/artifact/bin/torch-server.zip

**Comment by Jimmacle** [comment] 2019-11-11 21:48
Issue seems to be resolved based on reports in Discord

**Comment by Hallucine** [comment] 2019-11-13 10:54
I believe this is still happening if you use the stop command with save param as true, haven't tested false but it definitely still occurs with stop, fine with restart though (as the resolution said). Noticed it when also saving main SE config file changes before the next boot but likely unrelated)

**Comment by physicsjm32** [comment] 2019-11-13 10:56
I believe this is still happening if you use the stop command with save param as true, haven't tested false but it definitely still occurs with stop, fine with restart though (as the resolution said). Noticed it when also saving main SE config file changes before the next boot but likely unrelated)

**Comment by Jimmacle** [comment] 2019-11-13 14:14
Will test some more later today

**Comment by ruffst** [comment] 2019-11-16 04:41
I think the Torch resets the GPS coordinates and the factions when you press "Save Config", because before everything seemed to work fine. I also noticed that the Sanbox_config.sbc is saved in /.new/ but not loaded from it. Could this be related to that?

**Comment by ruffst** [comment] 2019-11-16 04:42
And yes, it's still happening. Had a lot of frustrated players last night.

**Comment by bodyboarder2528** [comment] 2019-11-18 06:16
how is this going?

**Comment by ruffst** [comment] 2019-11-20 05:57
when you change the config in the Torch UI i think. For example. We had a password protected Server. On the day when we wanted to release it to the public, I had to change the config by removing the password.  

I saved the world using !save and stopped the server. I removed the password and started it using the start Button. Thats it. After that all player (except me and another faction created earlier) lost their faction and GPS. Player who joined my faction recently where kicked out of my faction. (Maybe !save is ignored?)

Anyway. I did not touch the config since then. Changing the config-files directly using notepad works fine atm. Autorestart works as well.

**Comment by JimTheSoundman** [comment] 2019-11-23 00:25
This happened when I added a mod.   Do you think that had anything to do with it, or was that just coincidental?

**Comment by Jimmacle** [comment] 2019-11-23 02:19
If that consistently causes things to be reset then I'd consider it related. At this point I still don't have much idea of what's happening since none of the repro cases listed above have consistently triggered the bug in my own testing.

**Comment by Xechorizo** [comment] 2019-11-23 07:19
I tend to see it after !save, stop button click, start button click.

**Comment by Nehogo** [comment] 2019-11-25 19:53
Has there been been a fix for this? cause im running into this problem and its very frustrating.

**Comment by fightlessbirds** [comment] 2019-11-29 05:44
I was encountering this problem but resolved it by followed the advice above related to <IgnoreLastSession>, it should be set to false.

**Comment by fightlessbirds** [comment] 2019-11-29 23:49
Ok this is weird. Every time I save config with Torch it reverts <IgnoreLastSession> to true. Very frustrating.

**Comment by Jimmacle** [comment] 2019-11-29 23:52
It should not be set to false, otherwise the game ignores the world actually selected to load. Torch forces the option true on purpose. I was unable to reproduce the issue with IgnoreLastSession true so I don't think it's the source of the problem.

**Comment by fightlessbirds** [comment] 2019-11-30 06:52
1.3.1.95 has resolved the problem for me at least.

**Comment by fightlessbirds** [comment] 2019-12-01 05:58
Ok the clones have returned. :S And character toolbars have been partially reset again. This bug still happens regardless if \<IgnoreLastSession> is true or false.

**Comment by Jimmacle** [comment] 2019-12-08 02:17
Tentative fix added in 540b17448a8b2af63b57a843a382355526e1ddf0. Give the build server a few minutes then update Torch to see if the problem is resolved.

**Comment by bodyboarder2528** [comment] 2019-12-14 02:55
Did the fix turn out to be 100% fix as we need to stop the server to make some fixes and dont want it to revert back

**Comment by Jimmacle** [comment] 2019-12-14 03:33
Given the lack of confirmation from the reporters of the issue there's only one way to find out.

**Closed** 2019-12-14 19:57 UTC
Labels: bug

**Comment by kutovoy** [comment] 2019-12-25 23:52
1.3.1.99-master, all players lost all GPS points. no other things went missing it seems. I remember editing Essentials config. it would help if developer could add logging of trace to the log in the function which removes gps coords so we can track it down as the server is unsable lets be honest.

**Comment by kutovoy** [comment] 2019-12-26 05:05
an update... I shutdown server pressing Stop in Torch and exiting Torch then after editing torch config file and essentials config file to avoid using Torch GUI and pressing Start using newly launched Torch all GPS points are back. I suspect it overwritten config file yet again... this is a severe problem
