### ISSUE TITLE
Profiler causing crashes when ran 

### ISSUE THREAD

**Issue by CHEtheGREAT** [TorchAPI/Torch#354] opened 2019-10-15 23:44 UTC
- [*] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [*] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
Ran !profile with Profiler, expected a normal list of results.

### Observed Behavior
Server crashed with logs.

### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.

### Other Information
1st Crash:
https://pastebin.com/dz9XU3sp
2nd Crash:
https://pastebin.com/XG6AUL3e

World File:
https://drive.google.com/open?id=1ok_MEeNIbCfC8IpR-zoS8P1T3TDXoRQn

**Comment by Jimmacle** [comment] 2019-10-16 00:03
Duplicate of https://github.com/TorchAPI/Profiler/issues/10

**Closed by Jimmacle** 2019-10-16 00:03 UTC

**Comment by CHEtheGREAT** [comment] 2019-10-16 00:31
Hi, could you close the other one instead? I figured posting it here would get more attention because the other one's been up for about a week and hasnt' received any responses
