### ISSUE TITLE
Strange Crash 2x when starting server after updating torch/se... unknown reasons?

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#109] opened 2017-09-10 06:37 UTC
- [Doesn't happen in vanilla... so] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [Unsure if repro will be available] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [no] Is this a suggestion?

**Happens on latest torch/SE version. info should be in log for when it happened this time, but it has happened on the previous version as well. 

### Expected Behavior
What did you expect to happen?
-Server to start without issue?

### Observed Behavior
What actually happened?
This?! I'm not really sure tbh.
https://cdn.discordapp.com/attachments/262467504830414848/355656155650850816/EXCEPTIONNN.txt

### Steps to Reproduce
1. Updated server via manually copy/pasting torch files into directory, as well as concealment and essentials. 
2. Tried to repro but it seems to only happen when SE updates so far. 

What happened was, when I started the server after updating SE, then later Torch/Essentials/Concealment all together... I got the exception here:
https://cdn.discordapp.com/attachments/262467504830414848/355656155650850816/EXCEPTIONNN.txt
4. After completing this, I only re-started the server, and got the exception for the second time. 
5. Upon the third time... everything was fine, no exception. 

I've tried to re-produce it on LAN by making a new server instance and have no luck... 
It's happened once before with a similar exception but I did not see any exception the first time. 

### Other Information
exception: https://cdn.discordapp.com/attachments/262467504830414848/355656155650850816/EXCEPTIONNN.txt

this was the only exception i could find in the logs. other than the config being invalid or w/e from vanilla issues.

**Comment by Equinox-** [comment] 2017-09-10 06:40
Suspect that this issue is related to the console stream getting plugged up.  With WPF the console stream should be a pipe, and if it's not getting drained that would be a problem.  Try launching with `-nogui` and seeing if you can reproduce.

**Comment by XeroCreator** [comment] 2017-09-10 07:30
no dice.

**Comment by Equinox-** [comment] 2017-09-10 08:11
As in "no you couldn't reproduce it" or "no it still had the same issue"?

**Comment by XeroCreator** [comment] 2017-09-10 09:11
no dice as in no i couldn't reporoduce it. 
no dice is generally saying no. if it still had the same issue i'd be like YEAH I DID IT ... but no... i didn't do it.

**Comment by Equinox-** [comment] 2017-09-29 21:29
Will be addressed in #129

**Closed by Equinox-** 2017-09-29 21:29 UTC

**Comment by Varaxian** [comment] 2017-10-02 21:47
Reproduced:

When pasting files into the same directory that TORCH was previously, Windows Firewall faults. It is referencing the exact same file location, but isn't actually giving permissions to allow it through.

Resolve: 
Remove all instances of TORCH from Windows firewall COMPLETELY, then add them to the allow list again.

**Comment by XeroCreator** [comment] 2017-10-02 22:22
That might be related but I replace all torch files manually  and it only errors like this a few times and then stops and everything is fine. It's been reproduced with just updating SE, but again it's fine after 2-3 startups. Torch is run as admin as well, which I setup UAC to give permissions for.
I'm going to continue to update except try overwriting instead of manual delete and see if it happens again. 

That may be temporary solution but it could also just be your settings on uac. Either way this should already be fixed anyway.
