### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bennextmitchell** [TorchAPI/Torch#43] opened 2017-07-10 13:27 UTC
crash on loading up.
Log:

14:24:34.0781 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\BattleSrv\TorchConfig.xml
14:24:34.2103 [INFO] SteamCMD: Checking for DS updates.
14:24:35.1131 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:24:35.2142 [INFO] SteamCMD: -- type 'quit' to exit --
14:24:35.3163 [INFO] SteamCMD: Loading Steam API...OK.
14:24:35.4177 [INFO] SteamCMD: 
14:24:37.2423 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:24:37.3444 [INFO] SteamCMD: Waiting for user info...OK
14:24:38.8547 [INFO] SteamCMD: Success! App '298740' already up to date.
14:24:39.3502 [INFO] SteamCMD: 
14:24:41.4591 [INFO] Torch: RELEASE
14:24:41.4591 [INFO] Torch: Torch 1.0.182.329, SE 1.181.502
14:24:41.4591 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:24:41.4591 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\BattleSrv\
14:24:41.4591 [INFO] Torch: Init server 'Battle' at 'C:\Users\Administrator\Desktop\BattleSrv\Instance'
14:24:42.6195 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\ixardunp.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)
14:24:47.9913 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\BattleSrv\TorchConfig.xml
14:24:48.1104 [INFO] SteamCMD: Checking for DS updates.
14:24:48.7443 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:24:48.8464 [INFO] SteamCMD: -- type 'quit' to exit --
14:24:48.9475 [INFO] SteamCMD: Loading Steam API...OK.
14:24:49.0487 [INFO] SteamCMD: 
14:24:51.3062 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:24:52.7359 [INFO] SteamCMD: Waiting for user info...OK
14:24:53.1263 [INFO] SteamCMD: Success! App '298740' already up to date.
14:24:53.9090 [INFO] SteamCMD: 
14:24:54.3695 [INFO] Torch: RELEASE
14:24:54.3695 [INFO] Torch: Torch 1.0.182.329, SE 1.181.502
14:24:54.3695 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:24:54.3695 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\BattleSrv\
14:24:54.3695 [INFO] Torch: Init server 'Battle' at 'C:\Users\Administrator\Desktop\BattleSrv\Instance'
14:24:55.0402 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\kz14ocd5.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)
14:25:00.4383 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\BattleSrv\TorchConfig.xml
14:25:00.5555 [INFO] SteamCMD: Checking for DS updates.
14:25:01.1893 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:25:01.2914 [INFO] SteamCMD: -- type 'quit' to exit --
14:25:01.3925 [INFO] SteamCMD: Loading Steam API...OK.
14:25:01.9550 [INFO] Torch: RELEASE
14:25:01.9550 [INFO] Torch: Torch 1.0.182.329, SE 1.181.502
14:25:01.9550 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:25:01.9550 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\BattleSrv\
14:25:01.9550 [INFO] Torch: Init server 'Battle' at 'C:\Users\Administrator\Desktop\BattleSrv\Instance'
14:25:02.5226 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\ry4yqfoi.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)
14:25:06.9608 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\BattleSrv\TorchConfig.xml
14:25:07.0780 [INFO] SteamCMD: Checking for DS updates.
14:25:07.8041 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:25:07.9052 [INFO] SteamCMD: -- type 'quit' to exit --
14:25:08.0063 [INFO] SteamCMD: Loading Steam API...OK.
14:25:08.1078 [INFO] SteamCMD: 
14:25:09.8257 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:25:09.9272 [INFO] SteamCMD: Waiting for user info...OK
14:25:10.7020 [INFO] SteamCMD: Success! App '298740' already up to date.
14:25:10.9681 [INFO] SteamCMD: 
14:25:11.4296 [INFO] Torch: RELEASE
14:25:11.4296 [INFO] Torch: Torch 1.0.182.329, SE 1.181.502
14:25:11.4296 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:25:11.4296 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\BattleSrv\
14:25:11.4296 [INFO] Torch: Init server 'Battle' at 'C:\Users\Administrator\Desktop\BattleSrv\Instance'
14:25:12.0392 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\iv0zmwas.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)
14:25:17.3762 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\BattleSrv\TorchConfig.xml
14:25:17.4783 [INFO] SteamCMD: Checking for DS updates.
14:25:18.2034 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:25:18.3055 [INFO] SteamCMD: -- type 'quit' to exit --
14:25:18.4066 [INFO] SteamCMD: Loading Steam API...OK.
14:25:18.5079 [INFO] SteamCMD: 
14:25:22.9395 [INFO] SteamCMD: Connecting anonymously to Steam Public...threadtools.cpp (3294) : Assertion Failed: Illegal termination of worker thread 'CIPCServer::m_ThreadClient'

**Comment by Jimmacle** [comment] 2017-07-11 02:32
This looks like either a permissions issue or corrupt DS install. Try validating the app download through SteamCMD.

**Comment by Jimmacle** [comment] 2017-07-13 21:45
Closing this until you can verify that it's a reproducible issue with Torch.

**Closed by Jimmacle** 2017-07-13 21:45 UTC
