### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#139] opened 2017-10-04 08:31 UTC
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.2.0-43-g6f650c8 **SE Version:** 1.184.200

### Expected Behavior
Torch launch the Session
### Observed Behavior
Torch crashed.

### Steps to Reproduce
1. How did this issue get triggered?
2.Doenlosd the #21 staging build of torch. Open and run. Works fine, press'start' and sessions crashes
### Other Information
09:21:10.9191 [INFO] Torch: Starting server.
09:21:18.6047 [INFO] Torch.Session.TorchSessionManager: Starting new torch session for TakenWorld
09:21:25.5231 [ERROR] Torch.Session.TorchSessionManager: System.ArgumentException: Field 'ValidateAuthTicketResponse' defined on type 'VRage.Steam.MySteamGameServer' is not a field on the target object which is of type 'VRage.Steam.MySteamGameServer'.
   at System.Reflection.RtFieldInfo.CheckConsistency(Object target)
   at System.Reflection.RtFieldInfo.InternalGetValue(Object obj, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at Torch.Utils.ReflectedEventReplacer.<GetEventsInternal>d__17.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 342
   at Torch.Utils.ReflectedEventReplacer.Test(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 276
   at Torch.Utils.ReflectedEventReplacer.Replace(Delegate newCallback, Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 296
   at Torch.Server.Managers.MultiplayerManagerDedicated.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 65
   at Torch.Managers.DependencyManager.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 251
   at Torch.Session.TorchSession.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 41
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 99
09:21:29.0384 [INFO] Torch.Session.TorchSessionManager: Unloading torch session for TakenWorld
09:21:29.0474 [ERROR] Torch.Session.TorchSessionManager: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.EventInfo.RemoveEventHandler(Object target, Delegate handler)
   at Torch.Utils.ReflectedEventReplacer.<>c__DisplayClass8_0.<.ctor>b__3(Delegate x) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 251
   at Torch.Utils.ReflectedEventReplacer.Restore(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 318
   at Torch.Server.Managers.MultiplayerManagerDedicated.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 74
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.Session.TorchSession.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 46
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 138
09:21:29.0665 [FATAL] Initializer: System.Reflection.TargetException: Object does not match target type.
   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.EventInfo.RemoveEventHandler(Object target, Delegate handler)
   at Torch.Utils.ReflectedEventReplacer.<>c__DisplayClass8_0.<.ctor>b__3(Delegate x) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 251
   at Torch.Utils.ReflectedEventReplacer.Restore(Object instance) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Utils\ReflectedManager.cs:line 318
   at Torch.Server.Managers.MultiplayerManagerDedicated.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\MultiplayerManagerDedicated.cs:line 74
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.Session.TorchSession.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSession.cs:line 46
   at Torch.Session.TorchSessionManager.SessionUnloaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Session\TorchSessionManager.cs:line 144
   at System.Action.Invoke()
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at Torch.Server.TorchServer.Start() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\TorchServer.cs:line 156
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Equinox-** [comment] 2017-10-04 13:34
Duplicate of #128

**Closed** 2017-10-04 13:34 UTC
