### ISSUE TITLE
Suggestion: Hot Plug-ins

### ISSUE THREAD

**Issue by XeroCreator** [TorchAPI/Torch#166] opened 2017-11-04 11:27 UTC
Suggestion:
Hot Plug-ins meaning drag/drop and reload plugins without restarting server. 
SESE had this and it's honestly very nice to be able to replace plugins with newer versions w/o having to restart. 

This might also already be planned but here's the suggestion for it. 

suggest adding a save event when pressing reload before loading new plugins loaded in to prevent... well.. accidents.

**Comment by szczepix** [comment] 2017-11-04 13:21
Looks like be duplicated #162

**Comment by Equinox-** [comment] 2017-11-04 18:42
Not a duplicate of that issue.  Xero is referring to reloading plugins
without restarting the assembly.  That issue is likely just a "I installed
plugins wrong" issue

**Comment by Jimmacle** [comment] 2018-12-24 20:10
This is unlikely to be implemented because some plugin features are too invasive to reliably unload.

**Closed by Jimmacle** 2018-12-24 20:10 UTC
Labels: planned
