### ISSUE TITLE
Independent Console Always Opens again

### ISSUE THREAD

**Issue by Mr-Mors** [TorchAPI/Torch#292] opened 2019-03-03 06:39 UTC
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [X] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.21.59

### Expected Behavior
With:
false

You should not have an independent console

### Observed Behavior
What actually happened?

### Steps to Reproduce
Update torch
Open torch.
No plugins loaded still has issue

### Other Information
No errors to report in log.

**Comment by rexxar-tc** [comment] 2019-03-03 13:34
Can't reproduce. Delete your torch files and try again with a fresh copy from the website.

**Comment by JamieKG** [comment] 2019-03-03 14:20
This happens for me on the patron branch only

**Comment by rexxar-tc** [comment] 2019-03-04 00:55
Resolved in latest patron branch

**Closed by rexxar-tc** 2019-03-04 00:55 UTC
