### ISSUE TITLE
[BUG] Adding automated essentials commands causes crash when clicking on either of the time fields

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#62] opened 2017-07-30 22:55 UTC
**Torch Version:** 1.1.207.7 **SE Version:** 1.182.103

### Expected Behavior
Add an automated command to Essentials successfully

### Observed Behavior
Crashed upon clicking in either "Duetime" or "Period

### Steps to Reproduce
1. Launch TORCH (doesn't matter if you start the world or not)
2.) Plugins: Essentials
3.) Attempt to add a new automated command
4.) Crash on attempt to modify

**Comment by finne132** [comment] 2017-08-04 15:54
I can also confirm experiencing this bug, using the exact same above steps. 

Additionally, attempting to click the enable checkbox also results in a crash for me. Looks like trying to edit any field at all in that pane results in a crash.

**Comment by finne132** [comment] 2017-08-04 15:56
Looks like this thread is a dupe of https://github.com/TorchAPI/Torch/issues/59 which includes a log dump

**Comment by Jimmacle** [comment] 2017-08-17 16:26
I won't be fixing this particular bug because I'm going to rewrite the command scheduler entirely pretty soon.

**Closed by Jimmacle** 2017-08-17 16:26 UTC
Labels: wontfix
