### ISSUE TITLE
Error when trying to open New World and Open Plugin

### ISSUE THREAD

**Issue by doublee313** [TorchAPI/Torch#209] opened 2018-02-22 00:26 UTC
When I try to open New World or Add Plugins I get the following error:

https://snag.gy/7za2Su.jpg

**Torch Version:** Latest
### Expected Behavior
Create New World, Open Plugins to add

### Observed Behavior
Everytime

### Steps to Reproduce
1. Trying to click on button

Log File (error shown as I clicked the button):

19:23:22.0959 [INFO]   Torch.Managers.PluginManager: Loading plugins...
19:23:22.1359 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
19:23:28.8536 [INFO]   Torch.VRageGame: Setting up serializers
19:23:29.4397 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.PluginsControl.OpenFolder_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run()
   at Torch.Server.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
   at Torch.Server.Program.Main(String[] args)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.PluginsControl.OpenFolder_OnClick(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run()
   at Torch.Server.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
   at Torch.Server.Program.Main(String[] args)

**Comment by Jimmacle** [comment] 2018-02-22 00:29
I accidentally committed half-done code for the New World button so the crash is technically expected behavior there (oops). I wasn't aware of the plugin button causing a crash so I'll look at that and disable the New World button shortly.

**Comment by doublee313** [comment] 2018-02-22 01:08
Thanks for the reply. Do you suggest I setup the game world with the built in Dedicated then copy the save files over?

**Comment by Jimmacle** [comment] 2018-02-22 01:09
Yes, you can also create a world in singleplayer and copy it over from there.

**Comment by doublee313** [comment] 2018-02-22 01:20
Thanks. One last thing to make sure I'm doing this right. Lol.

1. Should I use Torch-Server\DedicatedServer64 or C:\SpaceEngineers\DedicatedServer64?
2. I think I should be using Torch-Server\Instances for Saves correct?
3. I pointed my .cfg file to use Torch-Server\Content\ for my maps which I hope is ok.

Thanks,
EE

**Comment by Jimmacle** [comment] 2018-02-22 01:23
Alright, those bugs should be fixed in e242ed6f1f1b461a5edca495c3078e4fa3628a50. Grab the latest Torch build from the website to double-check.

1. You should use the one that Torch set up in the same folder as Torch.Server.exe
2. Yes, provided that's the path that InstancePath points to in the config.
3. See above.

You can set up a recurring donation through [Patreon](https://patreon.com/torchapi) or one-time through [PayPal](https://paypal.me/jimmacle).

**Comment by Jimmacle** [comment] 2018-02-22 01:27
...or maybe not because an unrelated test is failing. Hold on while I fix that.

**Comment by doublee313** [comment] 2018-02-22 01:31
Thanks. Can you point to which files to DL? I don't have my GitHub sync on so do I need to install that?

**Comment by Jimmacle** [comment] 2018-02-22 01:36
Just download the latest `Server` version from here: http://torchapi.net/download/

**Comment by doublee313** [comment] 2018-02-22 01:36
Sorry, I looked to soon :) Thx

**Comment by Jimmacle** [comment] 2018-02-22 01:37
Yeah the build server decided that something was broken that's not actually broken so I had to fix it. Once you can confirm that those issues are solved I'll close this issue.

**Comment by doublee313** [comment] 2018-02-22 01:39
Thanks. I am a tester for Ark Server Manager (have beta tested for a few years and helped with suggestions) if you need another tester, etc. I will do my best to test each update.

**Comment by doublee313** [comment] 2018-02-22 01:41
Thanks Issues are fixed. Now I just need to get the Plugins working :) I copied them in the Plugins but not sure if I did it right. Couldn't find instructions. Thx :)

**Comment by Jimmacle** [comment] 2018-02-22 01:44
There's a short guide at https://torchapi.net/home/gettingstarted/. Once we hit the next goal on Patreon I'll be able to add a plugin directory section to the website to make it easier to find Torch plugins.

**Closed** 2018-02-22 02:01 UTC
Labels: bug, gui
