### ISSUE TITLE
[Suggestion] Add ability to scroll on settings panel

### ISSUE THREAD

**Issue by mbiddle** [TorchAPI/Torch#305] opened 2019-04-06 16:24 UTC
- [ ] Add the ability to scroll on settings panel on the Configuration tab while the server is running.

**Torch Version:** 1.3.1.25-master **SE Version:** 1.189.44

### Expected Behavior
I expected to be able to view the settings while the server is running.

### Observed Behavior
I could not scroll up or down on the settings panel

### Steps to Reproduce
1. Start the server
2. Try to scroll down on the settings panel

### Other Information
Talked to Jimmacle about this in Discord #help.

**Comment by Jimmacle** [comment] 2019-04-17 01:31
Duplicate of #281

**Closed by Jimmacle** 2019-04-17 01:31 UTC
