### ISSUE TITLE
Mods Not Saved

### ISSUE THREAD

**Issue by kamikaze0310** [TorchAPI/Torch#49] opened 2017-07-26 20:15 UTC
Mods in torch gui is not saved when modified. I can manually go into SpaceEngineers-Dedicated.cfg and put the modID in and it works but any changes in torch GUI is unaffected to the cfg file.

**Torch Version:** 1.1.207.7 **SE Version:** 1.182.19

### Expected Behavior
Any changes made in torch GUI in the mods section should reflect in SpaceEngineers-Dedicated.cfg

### Observed Behavior
Changes were made to torch GUI but were not saved in SpaceEngineers-Dedicated.cfg

**Comment by haximodor92** [comment] 2017-07-27 22:57
Yeah I have the same problem here, seems like a issue with 1.1.207.7

**Comment by Varaxian** [comment] 2017-07-28 18:08
Confirmed. GUI is broken

**Comment by Jimmacle** [comment] 2017-08-01 20:06
This should be fixed in the update released today.

**Comment by finne132** [comment] 2017-08-04 16:19
@Jimmacle This appears to still be an issue as of today. https://github.com/TorchAPI/Torch/issues/64 was opened up 2 days ago and appears to be a duplicate of this with an added mention of the admins field also not saving. 

@kamikaze0310 Can you help clue me in to the workaround you are using to launch the server WITH mods? Every time I start the server through Torch after having manually added the mods to the CFG file, Torch overwrites my changes before the server launches and no mods are ever loaded. 

Still playing with it to find a workaround myself

**Comment by kamikaze0310** [comment] 2017-08-04 16:33
@finne132 BEFORE you start torch, edit the CFG file and add the modID number to it. 
 _<Mods>
    <unsignedLong>932957557</unsignedLong>
    <unsignedLong>316190120</unsignedLong>
    <unsignedLong>644104483</unsignedLong>
    <unsignedLong>670717906</unsignedLong>
    <unsignedLong>487874776</unsignedLong>
    <unsignedLong>865309539</unsignedLong>
  </Mods>_

Then I launched torch and the Mods fields in torch GUI is reflected to what I have in this CFG file. Not sure if your doing it any different?

**Comment by Jimmacle** [comment] 2017-08-04 16:49
Are you clicking "Save Config?"

**Comment by kamikaze0310** [comment] 2017-08-04 16:52
@Jimmacle you mentioned that this is fixed on latest build...I actually having tested it since. Are u asking finne132?

**Comment by Jimmacle** [comment] 2017-08-04 16:55
I'm asking anyone experiencing the issue. I forgot to have the config save when you click Start after refactoring the instance manager code so I need to know if it's simply not saving automatically or if it's actually failing to save. There's a button on the config tab to save it manually.

**Comment by kamikaze0310** [comment] 2017-08-04 16:57
@Jimmacle gotcah....just tested, I hit save with the MODS field empty and hit start and it still loaded the existing mods in the CFG file.

**Comment by kamikaze0310** [comment] 2017-08-04 17:02
![untitled](https://user-images.githubusercontent.com/30474539/28978697-9a6f0d7a-790c-11e7-863b-9597ce507832.png)

Showing that it saves it......
11:58:41.3388 [INFO] InstanceManager: Saved dedicated config.
11:58:42.2759 [INFO] InstanceManager: Saved world config.
11:59:53.0807 [INFO] InstanceManager: Saved dedicated config.
11:59:53.1717 [INFO] InstanceManager: Saved world config.
11:59:53.1822 [INFO] Torch: Starting server.

**Comment by finne132** [comment] 2017-08-04 17:21
@Jimmacle sorry for the delay, was in a meeting there - yes I have been making sure to click Save Config. So here's my entire process (I haven't done kamikaze's workaround yet of loading the mods into the cfg file first). 

1. open torch 
2. paste in mod list 
3. Click save
------no change to cfg where the mods would be inserted------- 
4. Launch server

The workaround I tried that failed was... 

1. open torch 
2. edit cfg file, insert mod tags manually
3. save cfg file 
4. click to start server 
-----cfg file is overwritten, manually added mods tags are removed and server boots w/no mods---- 

I hope this is helpful. Going to try @kamikaze0310  method of adding mods to the cfg before launching now!

**Comment by finne132** [comment] 2017-08-04 17:33
@kamikaze0310 you are spot-on with your workaround thank you so much - works perfectly.

**Comment by Jimmacle** [comment] 2017-08-17 16:27
Fixed 82815f66e5384b8e8427d50720e23aebd3e10da0

**Closed by Jimmacle** 2017-08-17 16:27 UTC

**Comment by JemiloII** [comment] 2019-03-31 18:40
where is this suppose to be? The dedicated server? Some other cfg? I did a full search and don't see this anywhere.
